### ISSUE TITLE
Please add a LICENSE file 📜

### ISSUE THREAD

**Issue by ris-work** [elixir-webrtc/elixir-webrtc.github.io#1]
I have had this org/name recommended when talking about data channels in membrane_framework. I hope this supports WebRTC data channels like webrtc-rs. I have seen that none of the projects contain a LICENSE file. Please add it to the repository with the notices. All the best for being more awesome than the membrane framwork.

Thank you very much for doing this and my best wishes!

**Comment by mickel8** [comment]
Hi @ris-work,
I've added missing LICENSE files in all our repositories :slightly_smiling_face: 

> Thank you very much for doing this and my best wishes!

Thanks! :slightly_smiling_face:
